name: Deploy in VPS

on:
  workflow_dispatch:

  workflow_run:
    workflows: ["Push Docker Image"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            docker login -u ${{ vars.DOCKER_USER }} -p ${{ secrets.DOCKER_TOKEN }}
            docker stop ${{ vars.DOCKER_CONTAINER }} || true
            docker rm ${{ vars.DOCKER_CONTAINER }} || true
            docker rmi -f ${{ vars.DOCKER_USER }}/${{ vars.DOCKER_IMAGE }}:latest || true
            docker pull ${{ vars.DOCKER_USER }}/${{ vars.DOCKER_IMAGE }}:latest
            docker run -d --name '${{ vars.DOCKER_CONTAINER }}' \
              -e 'VITE_DISCORD_CLIENT_ID=${{ vars.VITE_DISCORD_CLIENT_ID }}' \
              -e 'VITE_DISCORD_REDIRECT_URI=${{ vars.VITE_DISCORD_REDIRECT_URI }}' \
              -e 'VITE_API_URL=${{ vars.VITE_API_URL }}' \
              -p '${{ vars.DOCKER_HOST_PORT }}:5173' \
              '${{ vars.DOCKER_USER }}/${{ vars.DOCKER_IMAGE }}:latest'
