name: Deploy in VPS

on:
  workflow_dispatch:

  workflow_run:
    workflows: ["Push Docker Image"]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ vars.VPS_HOST }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            cd ~
            rm -rf Lucy-dash
            git clone https://github.com/${{ github.repository }}.git
            cd Lucy-dash
            
            docker stop ${{ vars.DOCKER_CONTAINER }} || true
            docker rm ${{ vars.DOCKER_CONTAINER }} || true
            docker rmi -f lucy-dash:latest || true
            
            docker build \
              --build-arg VITE_DISCORD_CLIENT_ID='${{ vars.VITE_DISCORD_CLIENT_ID }}' \
              --build-arg VITE_DISCORD_REDIRECT_URI='${{ vars.VITE_DISCORD_REDIRECT_URI }}' \
              --build-arg VITE_API_URL='${{ vars.VITE_API_URL }}' \
              -t lucy-dash:latest .
            
            docker run -d --name '${{ vars.DOCKER_CONTAINER }}' \
              -p '${{ vars.DOCKER_HOST_PORT }}:5173' \
              lucy-dash:latest
